version: '3'

services:
  proxy:
    image: nginx:latest # use the latest version of nginx
    ports:
      - '8080:80' # hostPort: containerPort -> exposes port 80 on host and sent to port 80 on container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro #hostPath:containerPath:mode

  web:
    image: httpd # uses httpd latest
